Aws feature branch to merge
cabinetoffice/gender-pay-gap pull request #499
Opened 2022-10-31 10:38 UTC by LadunOmideyiSoftwire

Notes:
- Terraform files have to be at the root so can't be organised
- Locals work like variables and variables like environment variables
- We removed main 
- Logging and monitoring are located with their respective resources except for alarms
- Any value that has be changed has a comment next to it

2022-10-31 12:29 UTC, davidm-m requested changes
A few things I want to check up on. One thing I haven't commented on but would be nice is if all of the code comments like "change this on production" had some identifiable string (`QQ` is sometimes used for things like this) that's easy to search the codebase for so we know we've made all the necessary changes before putting this live.

2022-10-31 12:29 UTC, davidm-m commented on terraform/elasticbeanstalk.tf
> +    value     = "false"  // disabled. we create out own port 80 listener which redirects to https
Typo: "we create ou**r** own port 80 listener"

2022-10-31 12:29 UTC, davidm-m commented on terraform/loadtest.tfvars
> +cloudfront_alternate_domain_name = "ladun.me"
I think this one needs a reminder to change it

2022-10-31 12:29 UTC, davidm-m commented on terraform/loadtest.tfvars
> +env     = "loadtest"
Is the plan to have a load test environment running all the time?

2022-10-31 12:29 UTC, davidm-m commented on terraform/locals.tf
> +
Is this file doing anything? 😅

2022-10-31 12:29 UTC, davidm-m commented on terraform/variables.tf
> +  default     = "ladun.omideyi@softwire.com"
Can we make this the team email instead?

2022-10-31 16:39 UTC, LadunOmideyiSoftwire commented on GenderPayGap.WebUI/wwwroot/robots.txt
> +Disallow: /*
For the migration to make files non indexable. Removing as the site is going live tomorrow

2022-11-01 15:00 UTC, davidm-m approved these changes

2022-11-01 15:15 UTC, merged